Desymfony\Pokemon\Infrastructure\Persistence\Doctrine\Domain\Entity\DoctrinePokemon:
  table: pokemon
  type: entity
  repositoryClass: Desymfony\Pokemon\Infrastructure\Persistence\Doctrine\Domain\Repository\DoctrinePokemonRepository
  id:
    id:
      type: integer
      length: 11
      unsigned: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 100
    generation:
      type: integer
      unsigned: true
      nullable: false
  oneToMany:
    pokemonTypes:
      targetEntity: Desymfony\Pokemon\Infrastructure\Persistence\Doctrine\Domain\Entity\DoctrinePokemonType
      mappedBy: pokemon
